GasChannelWebApp/Controllers/InputDataVariantsController.cs
using GasChannelLib;
using GasChannelWebApp.Domain;
using GasChannelWebApp.Infrastructure;
using GasChannelWebApp.Models;
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GasChannelWebApp.Controllers
{
    [Authorize] // К контроллеру получают доступ только аутентифицированные пользователи.
    public class InputDataVariantsController : Controller
    {
        // Dependency Injection
        // Данные поля будут хранит ссылки на реальные репозитории или на тестовые в соответствии с параметрами переданными в конструктор
        IInputDataVariantsRepository _inputDataVariants;
        IVariantsRepository _variants;
        IUserProfileRepository _users;

        public InputDataVariantsController()
            : this(new DALContext())
        {
        }
        public InputDataVariantsController(IDALContext context)
        {
            _variants = context.Variants;
            _inputDataVariants = context.InputDataVariants;
            _users = context.Users;
        }

        public ActionResult Index()
        {
            ViewBag.ID_Variant = new SelectList(_variants.All.Where(t => t.Owner.ID_User == _users.CurrentUser.ID_User), "ID_Variant", "NameVariant");
            return View(_users.CurrentUser.InputDataVariants.ToList());
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "ClearTable")]
        public ActionResult Index(Object sender)
        {
            GasChannelDB _database = new GasChannelDB();
            _database.InputDataVariants.RemoveRange(_database.InputDataVariants.Where(o => o.Owner.ID_User == _users.CurrentUser.ID_User));
            _database.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "Filter")]
        public ActionResult Index(Variants variant)
        {
            if (variant.ID_Variant != 0) // если выбран элемент списка "Все", который прописан при формировании выпадающего списка в представлении Index
            {
                ViewBag.ID_Variant = new SelectList(_variants.All.Where(t => t.Owner.ID_User == _users.CurrentUser.ID_User), "ID_Variant", "NameVariant");
                return View(_users.CurrentUser.InputDataVariants.Where(t => t.ID_Variant == variant.ID_Variant).ToList());
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: /InputDataVariants/
        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "LoadTable")]
        public ActionResult Index(InputDataVariants inputDataVariants)
        {
            GasChannelDB _database = new GasChannelDB();

            #region --- Ввод тестовых данных в базу данных       

            int _ID_Variant_1 = _database.Variants.Where(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).First().ID_Variant;
            InputDataVariants inputDataVariants_1 = new InputDataVariants
            {
                ID_Variant = _ID_Variant_1,
                Kol_prod_gorenija = 19165,
                Ro_0 = 1.28,
                Ro_v = 1.29,
                H_pechi = 3.55,
                L_pechi = 2.15,
                T_fume = 1223,
                T_fume_v = 1198,
                L_vert = 1,
                b_vert = 0.7,
                H_vert = 3,
                lambda_vert = 0.05,
                L_bor_vert_rek = 11,
                Td_rek_fume_bor = 1176,
                Tv_bor = 293,
                H_bor = 2.15,
                L_bor = 6,
                T_rek = 450,
                L_rek = 1.4,
                W_rek = 2.5,
                d_trub_rek = 57,
                T_rek_vh = 1176,
                W0_rek = 4.8,                
                n_trub = 14,
                T_trub = 593,
                d_h_diag = 8,
                fi_s1 = 0.95,
                fi_s2 = 1,
                fi_d = 1.11,
                fi_t_st = 1.06,
                Owner = _users.CurrentUser
            };
            _inputDataVariants.InsertOrUpdate(inputDataVariants_1);
            _inputDataVariants.Save();

            #endregion --- Ввод тестовых данных в базу данных

            return RedirectToAction("Index");
        }
        public ActionResult Create()
        {
            ViewBag.ID_Variant = new SelectList(_variants.All.Where(t => t.Owner.ID_User == _users.CurrentUser.ID_User), "ID_Variant", "NameVariant");
            return View();
        }

        [HttpPost]
        public ActionResult Create(InputDataVariants inputDataVariants)
        {
            if (ModelState.IsValid)
            {
                inputDataVariants.Owner = _users.CurrentUser;
                _inputDataVariants.InsertOrUpdate(inputDataVariants);
                _inputDataVariants.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // GET: /InputDataVariants/Edit/1
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Edit(int id)
        {
            ViewBag.ID_Variant = new SelectList(_variants.All.Where(t => t.Owner.ID_User == _users.CurrentUser.ID_User), "ID_Variant", "NameVariant");
            return View(_inputDataVariants.All.FirstOrDefault(t => t.ID_InputDataVariant == id));
        }

        //
        // POST: /InputDataVariants/Edit/

        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        public ActionResult Edit(InputDataVariants inputDataVariants)
        {
            if (ModelState.IsValid)
            {
                _inputDataVariants.InsertOrUpdate(inputDataVariants);
                _inputDataVariants.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // Edit: /InputDataVariants/Delete/1
        // [Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Delete(int id)
        {
            return View(_inputDataVariants.All.FirstOrDefault(t => t.ID_InputDataVariant == id));
        }

        //
        // POST: /InputDataVariants/Delete/1
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _inputDataVariants.Remove(_inputDataVariants.All.FirstOrDefault(t => t.ID_InputDataVariant == id));
            _inputDataVariants.Save();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(_inputDataVariants.All.FirstOrDefault(t => t.ID_InputDataVariant == id));
        }

    }
}

GasChannelWebApp/Controllers/VariantsController.cs
using System;
using System.Net;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GasChannelWebApp.Domain;
using GasChannelWebApp.Infrastructure;
using GasChannelWebApp.Models;

namespace GasChannelWebApp.Controllers
{
    [Authorize]
    public class VariantsController : Controller
    {
        IVariantsRepository _variants;
        IUserProfileRepository _users;

        public VariantsController()
            : this(new DALContext())
        {
        }

        public VariantsController(IDALContext context)
        {
            _variants = context.Variants;
            _users = context.Users;
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "ClearTable")]
        public ActionResult Index(Object sender)
        {
            GasChannelDB _database = new GasChannelDB();
            _database.Variants.RemoveRange(_database.Variants.Where(o => o.Owner.ID_User == _users.CurrentUser.ID_User));
            _database.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "LoadTable")]
        public ActionResult Index(Variants variants)
        {
            #region --- Ввод тестовых данных в базу данных

            Variants var_1 = new Variants { NameVariant = "Вариант 1", DateVariant = new DateTime(2020, 11, 01), Owner = _users.CurrentUser };
            _variants.InsertOrUpdate(var_1);
            _variants.Save();

            #endregion --- Ввод тестовых данных в базу данных

            return RedirectToAction("Index");
        }



        // GET: Variants
        public ActionResult Index()
        {
            return View(_users.CurrentUser.Variants.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Variants variants)
        {
            if (ModelState.IsValid)
            {
                variants.Owner = _users.CurrentUser;
                _variants.InsertOrUpdate(variants);
                _variants.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // GET: /Variants/Edit/1
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Edit(int id)
        {
            return View(_variants.All.FirstOrDefault(t => t.ID_Variant == id));
        }

        //
        // POST: /Variants/Edit/

        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        public ActionResult Edit(Variants variants)
        {
            if (ModelState.IsValid)
            {
                _variants.InsertOrUpdate(variants);
                _variants.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // Edit: /Variants/Delete/1
        // [Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Delete(int id)
        {
            return View(_variants.All.FirstOrDefault(t => t.ID_Variant == id));
        }

        //
        // POST: /Variants/Delete/1
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _variants.Remove(_variants.All.FirstOrDefault(t => t.ID_Variant == id));
            _variants.Save();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(_variants.All.FirstOrDefault(t => t.ID_Variant == id));
        }
    }
}

GasChannelWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "О программе";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
    Автор: Григорий Федотов<br />
    @ViewBag.Assembly<br />
    2020 г.
</p>

GasChannelWebApp/Views/Home/Cabinet.cshtml
@{
    ViewBag.Title = "Личный кабинет пользователя";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<aside>
    <h3>Решение задачи</h3>
    <p>
        Данные, расчет и отображение результатов в табличной и графической формах
    </p>
    <ul>
        <li>@Html.ActionLink("Демонстрационный пример", "Demo", "Home")</li>
    </ul>

</aside>

<aside>
    <h3>Таблицы базы данных</h3>
    <p>
        Просмотр и редактирование данных в таблицах
    </p>
    <ul>
        <li>@Html.ActionLink("Справочник вариантов расчета", "Index", "Variants")</li>
        <li>@Html.ActionLink("Справочник исходных данных вариантов расчета", "Index", "InputDataVariants")</li>
    </ul>
</aside>

GasChannelWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакты";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    620002, Россия, г. Екатеринбург, ул. Мира, д. 28.<br />
    Кафедра "Теплофизика и информатика в металлургии", ИНМТ Уральский федеральный университет<br />
    <abbr title="Телефон">Телефон:</abbr>
    +7 (912) 277-34-97
</address>

<address>
    <strong>Техническая поддержка:</strong>   <a href="mailto:grinzya@yandex.ru">grinzya@yandex.ru</a><br />

</address>

GasChannelWebApp/Views/Home/Demo.cshtml
@model GasChannelWebApp.Domain.Variants

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    @using (Html.BeginForm("Demo", "Home", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.ID_Variant, "Выберите вариант исходных данных", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DropDownList("ID_Variant", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Variant, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" style="margin-left: auto; margin-top: 20px">
            <button type="submit" name="action" value="toApply" style="font-size: 16px" class="btn btn-primary">Применить</button>
        </div>

        <p>
        </p>

        <div class="container">
            <h2>Исходные данные</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Наименование показателя, ед. изм.</th>
                            <th>Величина</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Количество продуктов горения, м³/ч</td>
                            <td>@Html.TextBox("InputData.Kol_prod_gorenija", (double)(ViewBag.InputData.Kol_prod_gorenija), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Плотность дымовых газов, кг/м³</td>
                            <td>@Html.TextBox("InputData.Ro_0", (double)(ViewBag.InputData.Ro_0), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Плотность воздуха при Т=273°К, ρв, кг/м³</td>
                            <td>@Html.TextBox("InputData.Ro_v", (double)(ViewBag.InputData.Ro_v), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Высота рабочего пространства в конце печи, м</td>
                            <td>@Html.TextBox("InputData.H_pechi", (double)(ViewBag.InputData.H_pechi), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Ширина рабочего пространства в конце печи, м</td>
                            <td>@Html.TextBox("InputData.L_pechi", (double)(ViewBag.InputData.L_pechi), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Температура дыма в конце печи, К</td>
                            <td>@Html.TextBox("InputData.T_fume", (double)(ViewBag.InputData.T_fume), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Температура дыма в вертикальных каналах, К</td>
                            <td>@Html.TextBox("InputData.T_fume_v", (double)(ViewBag.InputData.T_fume_v), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Длина вертикальных каналов, м</td>
                            <td>@Html.TextBox("InputData.L_vert", (double)(ViewBag.InputData.L_vert), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Ширина, м</td>
                            <td>@Html.TextBox("InputData.b_vert", (double)(ViewBag.InputData.b_vert), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Высота вертикальных каналов, м</td>
                            <td>@Html.TextBox("InputData.H_vert", (double)(ViewBag.InputData.H_vert), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Коэффициент лямбда</td>
                            <td>@Html.TextBox("InputData.lambda_vert", (double)(ViewBag.InputData.lambda_vert), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Длина борова от вертикальных каналов до рекуператора, м</td>
                            <td>@Html.TextBox("InputData.L_bor_vert_rek", (double)(ViewBag.InputData.L_bor_vert_rek), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Температура дыма перед рекуператором, Tд рек</td>
                            <td>@Html.TextBox("InputData.Td_rek_fume_bor", (double)(ViewBag.InputData.Td_rek_fume_bor), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Температура окружающего воздуха, Тв, К</td>
                            <td>@Html.TextBox("InputData.Tv_bor", (double)(ViewBag.InputData.Tv_bor), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Высота борова, м</td>
                            <td>@Html.TextBox("InputData.H_bor", (double)(ViewBag.InputData.H_bor), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Длина борова, м</td>
                            <td>@Html.TextBox("InputData.L_bor", (double)(ViewBag.InputData.L_bor), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Падение температуры дыма в рекуператоре, к</td>
                            <td>@Html.TextBox("InputData.T_rek", (double)(ViewBag.InputData.T_rek), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Длина камеры для установки рекуператора, м</td>
                            <td>@Html.TextBox("InputData.L_rek", (double)(ViewBag.InputData.L_rek), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Ширина камеры для установки рекуператора, м</td>
                            <td>@Html.TextBox("InputData.W_rek", (double)(ViewBag.InputData.W_rek), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Диаметр труб, мм</td>
                            <td>@Html.TextBox("InputData.d_trub_rek", (double)(ViewBag.InputData.d_trub_rek), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Температура дыма на входе в рекуператор, Тр, К</td>
                            <td>@Html.TextBox("InputData.T_rek_vh", (double)(ViewBag.InputData.T_rek_vh), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Скорость движения дыма в рекуператоре, м/с</td>
                            <td>@Html.TextBox("InputData.W0_rek", (double)(ViewBag.InputData.W0_rek), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Число рядов труб по глубине пучка</td>
                            <td>@Html.TextBox("InputData.n_trub", (int)(ViewBag.InputData.n_trub), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Средняя температура стен труб</td>
                            <td>@Html.TextBox("InputData.T_trub", (double)(ViewBag.InputData.T_trub), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>Δh, м</td>
                            <td>@Html.TextBox("InputData.d_h_diag", (double)(ViewBag.InputData.d_h_diag), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>φs1</td>
                            <td>@Html.TextBox("InputData.fi_s1", (double)(ViewBag.InputData.fi_s1), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>φs2</td>
                            <td>@Html.TextBox("InputData.fi_s2", (double)(ViewBag.InputData.fi_s2), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>φd</td>
                            <td>@Html.TextBox("InputData.fi_d", (double)(ViewBag.InputData.fi_d), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>
                        <tr>
                            <td>φt ст</td>
                            <td>@Html.TextBox("InputData.fi_d", (double)(ViewBag.InputData.fi_d), htmlAttributes: new { type = "text", style = " width:100px; " })</td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>

        <div class="form-group" style="margin-left: auto; margin-top: 20px">
            @Html.TextBox("NameNewVariant", (string)(ViewBag.NameNewVariant))
            <button type="submit" name="action" value="toSaveAs" style="font-size: 16px" class="btn btn-primary">Сохранить новый вариант</button>
        </div>

        <p>
        </p>

        <div class="form-group" style="margin-left: auto; margin-top: 20px">
            <button type="submit" name="action" value="toSolver" style="font-size: 16px" class="btn btn-primary">Рассчитать</button>
        </div>
    }
</body>
</html>

GasChannelWebApp/Views/Home/Excel.cshtml
@model GasChannelWebApp.Models.InputDataModel

@{
    ViewBag.Title = "Excel";
}
@{ if (ViewBag.Result == "Невозможно сохранить файл")
    {
        <h2>@ViewBag.Result</h2>
    }
    else
    {
        <h2>Файл успешно сохранен!</h2>
    }
}

GasChannelWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная страница";
}